development:
      host: localhost
      adapter: mysql2
      database: bitla_dev
      port: 3306
      username: root
      password: root
      socket: /var/run/mysqld/mysqld.sock
      encoding: utf8